account:
  username: <%= ENV['SHOGICLUB24_USERNAME'] %>
  password: <%= ENV['SHOGICLUB24_PASSWORD'] %>

board:
  #base_url: https://www.shogidojo.net/event/relay/23/c
  #ids:
  #  - 6
  base_url: https://www.shogidojo.net/event/relay/24/c
  ids:
    - 23

twitter:
  consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %>
  access_token_secret: <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>

cache_data_file: ./post_cache.yaml
